### ISSUE TITLE
variable dhcp_ddns_unknown_clients = false breaks DHCP

### ISSUE THREAD

**Issue by pspacek** [pdellaert/dhcp_server#16]
Hello,

`dhcp_common_ddns_unknown_clients` introduced in f8d7e10162d4eedf14467363a585cc51125c6beb (and renamed to `dhcp_ddns_unknown_clients` in 253f7f82bf3190a2d4dfd68df5a775b1d8ae0e49) is not working as one might guess from `ddns` in the variable name.

When the option `dhcp_ddns_unknown_clients` is not present, it in the end adds directive `ignore unknown-clients;` into `dhcpd.conf`.

This has nothing to do with DDNS and simply refuses to give leases to clients without a host declaration in `dhcpd.conf`.

I believe that this is a mistake and that the option should be removed or replaced (but I do not know what would be the replacement).

**Comment by slgevens** [comment]
Hey, 

In my playbook, I use these variables like that : 

`dhcp_ddns_client_updates: true`
`dhcp_ddns_unknown_clients: true`

And appear like that after playing the playbook : 

`allow client-updates;`
`allow unknown-clients;`

**Comment by pspacek** [comment]
Yes, this is an workaround. The problem is that `dhcp_ddns_unknown_clients` has nothing to do with DDNS so the option is misleading and should be either replaced or removed altogether.

**Comment by pdellaert** [comment]
You are absolutely right, sorry about this bad piece of code, i'll have to do some better research next time
